name: easy_localization_csv_module
description: "module that provides setting up easy_localization with csv files"
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/easy_localization_csv_module

version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  june_flow_util:
  easy_localization:  #@add
  easy_localization_loader: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/module/easy_localization_csv_module/
    - assets/
  uses-material-design: true