name: easy_localization_csv_module
description: "module that provides setting up easy_localization with csv files"
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/easy_localization_csv_module

version: 0.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.2
  june_flow_util: ^0.8.19
  easy_localization: ^3.0.5 #@add
  easy_localization_loader: ^2.0.1 #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/module/easy_localization_csv_module/
    - assets/
  uses-material-design: true